# mission type
int64 mission_type

# common 
# float64 target_x
# float64 target_y

# start point of line to follow with
float64 start_x 

# start point of line to follow with
float64 start_y

# slope of followed line
float64 k

# intercept of followed line
float64 b

bool is_reverse

# coordination x of origin point of followed circle
float64 origin_x

# coordination y of origin point of followed circle
float64 origin_y

# radius
float64 r
